# Site settings
title: Cristina Negrean
email: negrean.cristina@gmail.com
description: Software Engineer
metadata:
  keywords: Cristina,Tech,Blog,Java,Spring,Microservices,Scala,DevOps
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://cristina.tech # the base hostname & protocol for your site
twitter_username: cristinanegrean
github_username:  cristinanegrean

# Configure Permalinks for pages, posts, or collections. Jekyll uses by default URI template: /:categories/:year/:month/:day/:title.html and I want “pretty URLs”
permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown
kramdown:
  input:              GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Use the following plug-ins
plugins:
  - jekyll
  - jekyll-paginate  # break the main listing of posts up into smaller lists and display them over multiple pages

# Pagination
paginate: 9

sass:
    sass_dir: _sass
    style: compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
