# Site settings
title: Cristina Negrean
email: negrean.cristina@gmail.com
description: Software Engineer
metadata:
  keywords: Cristina,Tech,Blog,Java,Spring,Microservices,Scala,DevOps
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cristinanegrean.github.io" # the base hostname & protocol for your site
twitter_username: cristinanegrean
github_username:  cristinanegrean
gems: [jekyll-paginate]
# Build settings
markdown: kramdown

# Pagination
paginate: 10

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
